export const WORDS = [
  'shower',
  'deputy',
  'bishop',
  'reader',
  'wording',
  'request',
  'racism',
  'ivory',
  'entertainment',
  'damn',
  'voucher',
  'conservation',
  'flatware',
  'shatter',
  'arrangement',
  'snuggle',
  'forecast',
  'adviser',
  'simplicity',
  'prayer',
  'seem',
  'kit',
  'trainer',
  'agent',
  'hide',
  'indoor',
  'compliance',
  'engine',
  'shortage',
  'shelf',
  'cafe',
  'behave',
  'guideline',
  'include',
  'produce',
  'diplomatic',
  'like',
  'residence',
  'specimen',
  'dog',
  'fade',
  'claim',
  'bend',
  'demonstrate',
  'closed',
  'row',
  'property',
  'nomination',
  'dirty',
  'arise',
];

export const TIME_IN_SECONDS = 1000;
export const TIMER = 30 * TIME_IN_SECONDS;
export const TIME_IN_MINUTES = TIMER / 1000 / 60;
export const AVERAGE_WORD_LENGTH = 5;
